version: "3"

services:
  
  app:
    container_name: allocation
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=allocation
      - DB_PASSWORD=allocation
      - DB_NAME=allocation
      - DB_PORT=5432
      - API_HOST=app
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "80:80"
      
  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      - POSTGRES_USER=allocation 
      - POSTGRES_PASSWORD=allocation
      - POSTGRES_DB=allocation
    ports: 
      - "5432:5432"