name : test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "build images"
        run: docker-compose -f docker-compose.yaml build

