name : test

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build a Image
      run: docker-compose -f docker-compose.yaml build
    - name: Unit Tests
      run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/unit
