name : test

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build a Image
      run: docker-compose -f docker-compose.yaml build
    - name: Compose Up
      run: docker-compose up -d app
    - name: Run Unit Tests
      run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/unit
    - name: Run Integration Tests
      run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/integration
    - name: Run e2e Tests
      run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/e2e
    - name: Linting
      run: make black