name : test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build a Image
      run: make build
    - name: Run Unit-Tests
      run: make unit-tests
    - name: Run Integration-Tests
      run: make integration-tests
    - name: Run e2e Tests
      run: make e2e-tests